name: Django-app workflow

on:
  push:
    branches: [working-branch]
  pull_request:
    branches: [working-branch]
	
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Выполняет деплой
          cd ${{ secrets.PATH }}
          sourse venv/bin/activate
          git pull
          python manage.py makemigrations
          python manage.py migrate
          sudo service ${{ secrets.GUNICORN }} restart
          sudo service nginx restart
